package handlers

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os/exec"
	"runtime"
	"strings"
)

// NetworkConfigRequest represents the configuration request for a network interface
type NetworkConfigRequest struct {
	Interface string   `json:"interface"`
	IP        string   `json:"ip"`
	Netmask   string   `json:"netmask"`
	Gateway   string   `json:"gateway"`
	DNS       []string `json:"dns"`
}

// SetInterfaceConfigHandler configures a network interface (Linux only)
func SetInterfaceConfigHandler(w http.ResponseWriter, r *http.Request) {
	// Only allow POST requests
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	// This feature is Linux-only
	if runtime.GOOS != "linux" {
		http.Error(w, "Network configuration is only available on Linux systems", http.StatusForbidden)
		return
	}

	var req NetworkConfigRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "Invalid request body", http.StatusBadRequest)
		return
	}

	// Validate required fields
	if req.Interface == "" || req.IP == "" || req.Netmask == "" {
		http.Error(w, "Interface, IP, and Netmask are required", http.StatusBadRequest)
		return
	}

	// Convert netmask to CIDR notation if needed
	cidr := netmaskToCIDR(req.Netmask)
	ipWithCIDR := fmt.Sprintf("%s/%d", req.IP, cidr)

	// Flush existing IP addresses on the interface
	flushCmd := exec.Command("ip", "addr", "flush", "dev", req.Interface)
	if output, err := flushCmd.CombinedOutput(); err != nil {
		http.Error(w, fmt.Sprintf("Failed to flush interface: %s - %s", err.Error(), string(output)), http.StatusInternalServerError)
		return
	}

	// Set the new IP address
	addCmd := exec.Command("ip", "addr", "add", ipWithCIDR, "dev", req.Interface)
	if output, err := addCmd.CombinedOutput(); err != nil {
		http.Error(w, fmt.Sprintf("Failed to set IP address: %s - %s", err.Error(), string(output)), http.StatusInternalServerError)
		return
	}

	// Set gateway if provided
	if req.Gateway != "" {
		// Delete default route first (ignore errors if none exists)
		exec.Command("ip", "route", "del", "default").Run()

		// Add new default route
		routeCmd := exec.Command("ip", "route", "add", "default", "via", req.Gateway, "dev", req.Interface)
		if output, err := routeCmd.CombinedOutput(); err != nil {
			http.Error(w, fmt.Sprintf("Failed to set gateway: %s - %s", err.Error(), string(output)), http.StatusInternalServerError)
			return
		}
	}

	// Set DNS if provided
	if len(req.DNS) > 0 {
		// Update /etc/resolv.conf
		resolvConf := "# Generated by Network Manager\n"
		for _, dns := range req.DNS {
			resolvConf += fmt.Sprintf("nameserver %s\n", dns)
		}

		// Write to resolv.conf using sh -c and echo
		writeCmd := exec.Command("sh", "-c", fmt.Sprintf("echo '%s' > /etc/resolv.conf", resolvConf))
		if output, err := writeCmd.CombinedOutput(); err != nil {
			// Log warning but don't fail the request
			fmt.Printf("Warning: Failed to update DNS: %s - %s\n", err.Error(), string(output))
		}
	}

	// Return success
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	json.NewEncoder(w).Encode(map[string]string{
		"status":  "success",
		"message": fmt.Sprintf("Interface %s configured successfully", req.Interface),
	})
}

// netmaskToCIDR converts a subnet mask to CIDR notation
func netmaskToCIDR(netmask string) int {
	parts := strings.Split(netmask, ".")
	if len(parts) != 4 {
		return 24 // default
	}

	cidr := 0
	for _, part := range parts {
		var octet int
		fmt.Sscanf(part, "%d", &octet)
		for octet > 0 {
			if octet&1 == 1 {
				cidr++
			}
			octet >>= 1
		}
	}
	return cidr
}
